
import { FoodItem } from './types';

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: '1',
    name: 'Glacial Ember Burger',
    category: 'Burger',
    price: 18.99,
    description: 'Double-stacked wagyu beef with truffle aioli, charred heirloom tomatoes, and aged white cheddar on a toasted black brioche bun.',
    calories: 850,
    prepTime: '15-20 min',
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Midnight Truffle Pizza',
    category: 'Pizza',
    price: 24.50,
    description: 'Artisan Neapolitan crust topped with fresh burrata, wild porcini mushrooms, black truffle oil, and organic basil.',
    calories: 1100,
    prepTime: '20-25 min',
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Neon Sunset Elixir',
    category: 'Drink',
    price: 9.99,
    description: 'Cold-pressed dragon fruit and yuzu blend, infused with sparkling botanical essences and topped with edible gold leaf.',
    calories: 65,
    prepTime: '5 min',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Volcanic Sea Salt Fries',
    category: 'Fries',
    price: 8.50,
    description: 'Hand-cut triple-cooked Idaho potatoes tossed in Icelandic volcanic sea salt and fresh rosemary sprigs.',
    calories: 420,
    prepTime: '10 min',
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Nebula Chocolate Dome',
    category: 'Dessert',
    price: 14.99,
    description: 'A delicate dark chocolate sphere that melts away to reveal a heart of salted caramel mousse and hazelnut praline.',
    calories: 580,
    prepTime: '12 min',
    rating: 5.0,
  },
  {
    id: '6',
    name: 'Aether Wagyu Ribeye',
    category: 'Steak',
    price: 42.00,
    description: 'A5 Grade Wagyu ribeye, pan-seared with garlic-infused bone marrow butter and served with roasted heirloom carrots.',
    calories: 950,
    prepTime: '30 min',
    rating: 4.9,
  },
  {
    id: '7',
    name: 'Solaris Saffron Tagliatelle',
    category: 'Pasta',
    price: 28.00,
    description: 'Handmade saffron pasta tossed in a champagne cream sauce with butter-poached lobster and chive oil.',
    calories: 720,
    prepTime: '18 min',
    rating: 4.8,
  },
  {
    id: '8',
    name: 'Zenith Bluefin Sashimi',
    category: 'Sushi',
    price: 36.50,
    description: 'Premium cuts of Bluefin O-Toro served with hand-grated fresh wasabi and 25-year aged soy sauce.',
    calories: 310,
    prepTime: '15 min',
    rating: 4.9,
  },
  {
    id: '9',
    name: 'Void Umami Ramen',
    category: 'Ramen',
    price: 22.00,
    description: '24-hour tonkotsu broth darkened with charred garlic oil, served with 72-hour braised pork belly and an ajitsuke tamago.',
    calories: 980,
    prepTime: '15 min',
    rating: 4.9,
  },
  {
    id: '10',
    name: 'Prism Birria Tacos',
    category: 'Taco',
    price: 16.50,
    description: 'Three blue corn tortillas stuffed with slow-braised short rib, melted Oaxaca cheese, and served with a rich consommé.',
    calories: 640,
    prepTime: '12 min',
    rating: 4.7,
  },
  {
    id: '11',
    name: 'Obsidian Pepper Steak',
    category: 'Steak',
    price: 38.00,
    description: 'Peppercorn-crusted filet mignon flamed with cognac and served with silky parsnip purée and crispy leeks.',
    calories: 820,
    prepTime: '25 min',
    rating: 4.8,
  },
  {
    id: '12',
    name: 'Golden Saké Salmon',
    category: 'Sushi',
    price: 32.00,
    description: 'King Salmon nigiri lightly torched with saké-miso glaze and topped with marinated salmon roe.',
    calories: 450,
    prepTime: '15 min',
    rating: 5.0,
  }
];
